### ISSUE TITLE
Once a pointer?

### ISSUE THREAD

**Issue by StevenACoffman** [joncalhoun/twg#1]
I have been following your course, but I noticed that my linter sometimes complains [that on this line](https://github.com/joncalhoun/twg/blob/master/app/app.go#L16) this is a potential copy by value of a lock.  If I change it to a pointer, and [insert here a defensive](https://github.com/joncalhoun/twg/blob/master/app/app.go#L20):
```
	if a.once == nil {
		a.once = &sync.Once{}
	}
```
Then the linter quiets down, but this is less elegant than before. What do you think?

**Comment by joncalhoun** [comment]
iirc this isn't an issue in this particular code because I'm not passing the server around by value so this never gets copied. 

Your solution is one way to handle it, but keep in mind that it probably makes the `Server` type susceptible to race conditions. If two goroutines both call `ServeHTTP` or any other method that does this `if a.once == nil` check it could be a race condition.

(Sidenote - I have no idea why that method receiver variable is named `a` instead of something like `s` or `server` 😦 )

If I was changing the code now, I would probably do this:

```go
func NewServer() *Server {
  return &Server{nil, &sync.Once{}}
}

type Server struct {
	mux  *http.ServeMux
	once *sync.Once
}
```

*Disclaimer: I didn't test this code at all, just what I'm thinking as I read this*

**Comment by StevenACoffman** [comment]
The race condition is a very good point, and as is typical, your solution is elegant. I've been enjoying your courses immensely by the way. I find this course has paired well with the [Ardan Labs service training](https://github.com/ardanlabs/service-training) I've also been working through. Thanks for your response, and your excellent courses!
